### PR TITLE
fix copyable command

### PR DESCRIPTION
**Pull request by elvece**

### CODE REVIEW

**Comment by chrisguida** [comment]
This doesn't seem to affect anything... Can you describe what problem this fixes? Or is this just a formatting change? I agree it does look cleaner.

**Review by chrisguida — COMMENTED** [review]
see comment

**Comment by elvece** [comment]
> This doesn't seem to affect anything... Can you describe what problem this fixes? Or is this just a formatting change? I agree it does look cleaner.

The command needs the space between the x and localhost to properly run.

**Comment by chrisguida** [comment]
Apparently this affects: 

`macOS catalina 10.15.7 - zsh shell`

Merging.

**Pull request merged**
